"""initial_schema

Revision ID: 835754d37f03
Revises: 
Create Date: 2026-03-28 05:44:05.790461-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835754d37f03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('granary_capacity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level'),
    sa.UniqueConstraint('level', name='uq_granary_level')
    )
    op.create_table('map_tile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('is_constructible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('x', 'y', name='uq_tile_coordinates')
    )
    op.create_table('resources_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('WOOD', 'CLAY', 'IRON', 'CROP', name='resource'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tribe_attributes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('ROMANS', 'TEUTONS', 'GAULS', name='tribe'), nullable=False),
    sa.Column('bonus', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('warehouse_capacity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level'),
    sa.UniqueConstraint('level', name='uq_warehouse_level')
    )
    op.create_table('building_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('tribe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribe_attributes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'tribe_id', name='uq_buildingtype_name_tribe')
    )
    op.create_table('map_tile_resource_layout',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('map_tile_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['map_tile_id'], ['map_tile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_tile_id', 'resource_type_id', name='uq_tile_resource')
    )
    op.create_table('production',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('production_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type_id', 'level', name='uq_resource_level')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('tribe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribe_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('building_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_type_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('construction_time', sa.Integer(), nullable=False),
    sa.Column('population_required', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_type_id'], ['building_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_type_id', 'level', name='uq_building_type_level')
    )
    op.create_table('village',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('map_tile_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['map_tile_id'], ['map_tile.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_tile_id')
    )
    op.create_table('building_prerequisite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_level_id', sa.Integer(), nullable=False),
    sa.Column('required_building_type_id', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_level_id'], ['building_level.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['required_building_type_id'], ['building_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_level_id', 'required_building_type_id', name='uq_building_level_requirement')
    )
    op.create_table('building_upgrade_resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_level_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_level_id'], ['building_level.id'], ),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_level_id', 'resource_type_id', name='uq_building_upgrade')
    )
    op.create_index(op.f('ix_building_upgrade_resource_building_level_id'), 'building_upgrade_resource', ['building_level_id'], unique=False)
    op.create_table('village_farm_plots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=False),
    sa.Column('farm_number', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['village.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('village_id', 'resource_type_id', 'farm_number', name='uq_village_farm')
    )
    op.create_table('village_resource_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=False),
    sa.Column('stored_amount', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['village.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('village_id', 'resource_type_id', name='uq_village_resource')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('village_resource_storage')
    op.drop_table('village_farm_plots')
    op.drop_index(op.f('ix_building_upgrade_resource_building_level_id'), table_name='building_upgrade_resource')
    op.drop_table('building_upgrade_resource')
    op.drop_table('building_prerequisite')
    op.drop_table('village')
    op.drop_table('building_level')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('production')
    op.drop_table('map_tile_resource_layout')
    op.drop_table('building_type')
    op.drop_table('warehouse_capacity')
    op.drop_table('tribe_attributes')
    op.drop_table('resources_types')
    op.drop_table('map_tile')
    op.drop_table('granary_capacity')
    # ### end Alembic commands ###
