[tool.poetry]
name = "vallorium-backend"
version = "0.1.0"
description = "Travian-like backend (FastAPI + SQLAlchemy)"
authors = ["Your Name <you@example.com>"]
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.13"

fastapi = "^0.116"
pydantic = "^2.8"
pydantic-settings = "^2.0"
uvicorn = { extras = ["standard"], version = "^0.35" }

sqlalchemy = "^2.0"
alembic = "^1.16"

psycopg = { extras = ["binary"], version = "^3.2" }
passlib = {version = "1.7.4", extras = ["bcrypt"]}
pyjwt = "^2.10"
python-multipart = "^0.0.20"
celery = "^5.5"
psycopg2 = "^2.9.12"
bcrypt = "4.0.1"
