[tool.poetry]
name = "vallorium-backend"
version = "0.1.0"
description = "Travian-like backend (FastAPI + SQLAlchemy)"
authors = ["Your Name <you@example.com>"]
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.13"

fastapi = "^0.116"
pydantic = "^2.8"
pydantic-settings = "^2.0"
uvicorn = { extras = ["standard"], version = "^0.35" }

sqlalchemy = "^2.0"
alembic = "^1.16"

psycopg = { extras = ["binary"], version = "^3.2" }
passlib = {version = "1.7.4", extras = ["bcrypt"]}
pyjwt = "^2.10"
python-multipart = "^0.0.20"
celery = {version = "^5.5", extras = ["redis"]}
bcrypt = "4.0.1"
authlib = "^1.7.2"
httpx = "^0.28.1"
jinja2 = "^3.1.6"
itsdangerous = "^2.2.0"
sqlalchemy-utils = "^0.42.1"
python-dateutil = "^2.9.0.post0"
pyyaml = "^6.0.3"
faker = "^40.23.0"
email-validator = "^2.3.0"

[tool.poetry.group.dev.dependencies]
ipython = "^9.15.0"

