"""add tribe metadata and advantages

Revision ID: 00ab47a85593
Revises: f6d4cc2afac0
Create Date: 2026-08-14 23:02:12.452882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ab47a85593'
down_revision = 'f6d4cc2afac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tribe_advantage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tribe_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_tribe_advantage_position_non_negative'),
    sa.ForeignKeyConstraint(['tribe_id'], ['tribe_attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tribe_id', 'code', name='uq_tribe_advantage_code')
    )
    op.create_index(op.f('ix_tribe_advantage_tribe_id'), 'tribe_advantage', ['tribe_id'], unique=False)
    op.add_column('tribe_attributes', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('tribe_attributes', sa.Column('playstyle', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tribe_attributes', 'playstyle')
    op.drop_column('tribe_attributes', 'description')
    op.drop_index(op.f('ix_tribe_advantage_tribe_id'), table_name='tribe_advantage')
    op.drop_table('tribe_advantage')
    # ### end Alembic commands ###
