"""add tribe metadata and advantages

Revision ID: 4c4001bd893d
Revises: 89b10b08a737
Create Date: 2026-08-15 21:23:51.932183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4001bd893d'
down_revision = '89b10b08a737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', name='uq_idempotency_request_scope_key')
    )
    op.create_index(op.f('ix_idempotency_request_created_at'), 'idempotency_request', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idempotency_request_created_at'), table_name='idempotency_request')
    op.drop_table('idempotency_request')
    # ### end Alembic commands ###
