"""add farm upgrade completion index

Revision ID: 4c7ce0d9ff50
Revises: c28d876c0f69
Create Date: 2026-08-30 08:56:11.243128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c7ce0d9ff50'
down_revision = 'c28d876c0f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_farm_upgrade_status_completes_at', 'village_farm_upgrade', ['status', 'completes_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_farm_upgrade_status_completes_at', table_name='village_farm_upgrade')
    # ### end Alembic commands ###
