"""add map tile types and farm slot layouts

Revision ID: 89b10b08a737
Revises: 00ab47a85593
Create Date: 2026-08-15 16:00:22.812134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b10b08a737'
down_revision = '00ab47a85593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_tile_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('starter_eligible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('map_tile_type_farm_slot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('map_tile_type_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('slot_number BETWEEN 1 AND 18', name='ck_map_tile_type_farm_slot_range'),
    sa.ForeignKeyConstraint(['map_tile_type_id'], ['map_tile_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_tile_type_id', 'slot_number', name='uq_map_tile_type_farm_slot')
    )
    op.create_index(op.f('ix_map_tile_type_farm_slot_map_tile_type_id'), 'map_tile_type_farm_slot', ['map_tile_type_id'], unique=False)
    op.drop_table('map_tile_resource_layout')
    op.add_column('map_tile', sa.Column('map_tile_type_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_map_tile_map_tile_type_id'), 'map_tile', ['map_tile_type_id'], unique=False)
    op.create_foreign_key(None, 'map_tile', 'map_tile_type', ['map_tile_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'map_tile', type_='foreignkey')
    op.drop_index(op.f('ix_map_tile_map_tile_type_id'), table_name='map_tile')
    op.drop_column('map_tile', 'map_tile_type_id')
    op.create_table('map_tile_resource_layout',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('map_tile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['map_tile_id'], ['map_tile.id'], name=op.f('map_tile_resource_layout_map_tile_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], name=op.f('map_tile_resource_layout_resource_type_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('map_tile_resource_layout_pkey')),
    sa.UniqueConstraint('map_tile_id', 'resource_type_id', name=op.f('uq_tile_resource'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_map_tile_type_farm_slot_map_tile_type_id'), table_name='map_tile_type_farm_slot')
    op.drop_table('map_tile_type_farm_slot')
    op.drop_table('map_tile_type')
    # ### end Alembic commands ###
