"""added partial unique index on village farm plot

Revision ID: c28d876c0f69
Revises: 4c4001bd893d
Create Date: 2026-08-30 08:00:25.266391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28d876c0f69'
down_revision = '4c4001bd893d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_farm_upgrade_active_per_plot', 'village_farm_upgrade', ['village_farm_plot_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'in_progress')"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_farm_upgrade_active_per_plot', table_name='village_farm_upgrade', postgresql_where=sa.text("status IN ('queued', 'in_progress')"))
    # ### end Alembic commands ###
