"""add farm levels upgrade jobs and resource ledger

Revision ID: f6d4cc2afac0
Revises: 965933010fe7
Create Date: 2026-07-05 14:07:32.118832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6d4cc2afac0'
down_revision = '965933010fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_resource_type_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('production_per_hour', sa.Integer(), nullable=False),
    sa.Column('construction_time_seconds', sa.Integer(), nullable=False),
    sa.CheckConstraint('construction_time_seconds >= 0', name='ck_farm_time_non_negative'),
    sa.CheckConstraint('level >= 0', name='ck_farm_level_non_negative'),
    sa.CheckConstraint('production_per_hour >= 0', name='ck_farm_production_non_negative'),
    sa.ForeignKeyConstraint(['farm_resource_type_id'], ['resources_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_resource_type_id', 'level', name='uq_farm_resource_level')
    )
    op.create_index(op.f('ix_farm_level_farm_resource_type_id'), 'farm_level', ['farm_resource_type_id'], unique=False)
    op.create_table('farm_level_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_level_id', sa.Integer(), nullable=False),
    sa.Column('payment_resource_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_farm_level_cost_positive'),
    sa.ForeignKeyConstraint(['farm_level_id'], ['farm_level.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_resource_type_id'], ['resources_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_level_id', 'payment_resource_type_id', name='uq_farm_level_cost_resource')
    )
    op.create_index(op.f('ix_farm_level_cost_farm_level_id'), 'farm_level_cost', ['farm_level_id'], unique=False)
    op.create_table('building_level_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('building_level_id', sa.Integer(), nullable=False),
    sa.Column('payment_resource_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_building_level_cost_positive'),
    sa.ForeignKeyConstraint(['building_level_id'], ['building_level.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_resource_type_id'], ['resources_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('building_level_id', 'payment_resource_type_id', name='uq_building_level_cost_resource')
    )
    op.create_index(op.f('ix_building_level_cost_building_level_id'), 'building_level_cost', ['building_level_id'], unique=False)
    op.create_table('village_building',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('building_type_id', sa.Integer(), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.CheckConstraint('level >= 0', name='ck_village_building_level_non_negative'),
    sa.CheckConstraint('slot_number >= 1', name='ck_village_building_slot_positive'),
    sa.ForeignKeyConstraint(['building_type_id'], ['building_type.id'], ),
    sa.ForeignKeyConstraint(['village_id'], ['village.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('village_id', 'slot_number', name='uq_village_building_slot')
    )
    op.create_index(op.f('ix_village_building_village_id'), 'village_building', ['village_id'], unique=False)
    op.create_table('village_resource_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('starting_resources', 'farm_upgrade', 'building_upgrade', 'troop_training', 'market_send', 'market_receive', 'quest_reward', 'raid_loot', 'refund', 'admin_adjustment', name='resource_transaction_type_enum', native_enum=False, length=40), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['village_id'], ['village.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('village_id', 'idempotency_key', name='uq_village_resource_transaction_idempotency')
    )
    op.create_index('ix_resource_transaction_source', 'village_resource_transaction', ['source_type', 'source_id'], unique=False)
    op.create_index(op.f('ix_village_resource_transaction_created_at'), 'village_resource_transaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_village_resource_transaction_transaction_type'), 'village_resource_transaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_village_resource_transaction_village_id'), 'village_resource_transaction', ['village_id'], unique=False)
    op.create_table('village_building_upgrade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_building_id', sa.Integer(), nullable=False),
    sa.Column('from_level', sa.Integer(), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'in_progress', 'completed', 'cancelled', name='building_upgrade_status_enum', native_enum=False, length=20), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('actual_duration_seconds >= 0', name='ck_building_upgrade_duration_non_negative'),
    sa.CheckConstraint('from_level >= 0', name='ck_building_upgrade_from_level_non_negative'),
    sa.CheckConstraint('target_level = from_level + 1', name='ck_building_upgrade_next_level'),
    sa.ForeignKeyConstraint(['village_building_id'], ['village_building.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_building_upgrade_target_status', 'village_building_upgrade', ['village_building_id', 'status'], unique=False)
    op.create_index(op.f('ix_village_building_upgrade_completes_at'), 'village_building_upgrade', ['completes_at'], unique=False)
    op.create_index(op.f('ix_village_building_upgrade_status'), 'village_building_upgrade', ['status'], unique=False)
    op.create_index(op.f('ix_village_building_upgrade_village_building_id'), 'village_building_upgrade', ['village_building_id'], unique=False)
    op.create_table('village_farm_upgrade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('village_farm_plot_id', sa.Integer(), nullable=False),
    sa.Column('from_level', sa.Integer(), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'in_progress', 'completed', 'cancelled', name='upgrade_status_enum', native_enum=False, length=20), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('actual_duration_seconds >= 0', name='ck_farm_upgrade_duration_non_negative'),
    sa.CheckConstraint('from_level >= 0', name='ck_farm_upgrade_from_level_non_negative'),
    sa.CheckConstraint('target_level = from_level + 1', name='ck_farm_upgrade_next_level'),
    sa.ForeignKeyConstraint(['village_farm_plot_id'], ['village_farm_plots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_farm_upgrade_plot_status', 'village_farm_upgrade', ['village_farm_plot_id', 'status'], unique=False)
    op.create_index(op.f('ix_village_farm_upgrade_completes_at'), 'village_farm_upgrade', ['completes_at'], unique=False)
    op.create_index(op.f('ix_village_farm_upgrade_status'), 'village_farm_upgrade', ['status'], unique=False)
    op.create_index(op.f('ix_village_farm_upgrade_village_farm_plot_id'), 'village_farm_upgrade', ['village_farm_plot_id'], unique=False)
    op.create_table('village_resource_transaction_entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('resource_type_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('balance_before', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.CheckConstraint('balance_after = balance_before + delta', name='ck_resource_transaction_balance_math'),
    sa.CheckConstraint('balance_after >= 0', name='ck_resource_transaction_after_non_negative'),
    sa.CheckConstraint('balance_before >= 0', name='ck_resource_transaction_before_non_negative'),
    sa.CheckConstraint('delta <> 0', name='ck_resource_transaction_delta_non_zero'),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['village_resource_transaction.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'resource_type_id', name='uq_resource_transaction_entry_resource')
    )
    op.create_index(op.f('ix_village_resource_transaction_entry_transaction_id'), 'village_resource_transaction_entry', ['transaction_id'], unique=False)
    op.drop_index(op.f('ix_building_upgrade_resource_building_level_id'), table_name='building_upgrade_resource')
    op.drop_table('building_upgrade_resource')
    op.drop_table('production')
    op.add_column('building_level', sa.Column('construction_time_seconds', sa.Integer(), nullable=False))
    op.add_column('building_level', sa.Column('population_increase', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_building_level_building_type_id'), 'building_level', ['building_type_id'], unique=False)
    op.drop_constraint(op.f('building_level_building_type_id_fkey'), 'building_level', type_='foreignkey')
    op.create_foreign_key(None, 'building_level', 'building_type', ['building_type_id'], ['id'], ondelete='CASCADE')
    op.drop_column('building_level', 'population_required')
    op.drop_column('building_level', 'construction_time')
    op.drop_constraint(op.f('uq_buildingtype_name_tribe'), 'building_type', type_='unique')
    op.create_unique_constraint('uq_building_type_name_tribe', 'building_type', ['name', 'tribe_id'])
    op.alter_column('resources_types', 'name',
               existing_type=postgresql.ENUM('WOOD', 'CLAY', 'IRON', 'CROP', name='resource'),
               type_=sa.Enum('Wood', 'Clay', 'Iron', 'Crop', name='resource_enum', native_enum=False, length=20),
               existing_nullable=False)
    op.alter_column('tribe_attributes', 'name',
               existing_type=postgresql.ENUM('ROMANS', 'TEUTONS', 'GAULS', name='tribe'),
               type_=sa.Enum('Romans', 'Teutons', 'Gauls', name='tribe_enum', native_enum=False, length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.alter_column('village', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_village_owner_id'), 'village', ['owner_id'], unique=False)
    op.create_unique_constraint('uq_owner_village_name', 'village', ['owner_id', 'name'])
    op.drop_constraint(op.f('uq_village_farm'), 'village_farm_plots', type_='unique')
    op.create_index(op.f('ix_village_farm_plots_village_id'), 'village_farm_plots', ['village_id'], unique=False)
    op.create_unique_constraint('uq_village_farm_slot', 'village_farm_plots', ['village_id', 'farm_number'])
    op.drop_constraint(op.f('village_farm_plots_village_id_fkey'), 'village_farm_plots', type_='foreignkey')
    op.create_foreign_key(None, 'village_farm_plots', 'village', ['village_id'], ['id'], ondelete='CASCADE')
    op.alter_column('village_resource_storage', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_village_resource_storage_village_id'), 'village_resource_storage', ['village_id'], unique=False)
    op.drop_constraint(op.f('village_resource_storage_village_id_fkey'), 'village_resource_storage', type_='foreignkey')
    op.create_foreign_key(None, 'village_resource_storage', 'village', ['village_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'village_resource_storage', type_='foreignkey')
    op.create_foreign_key(op.f('village_resource_storage_village_id_fkey'), 'village_resource_storage', 'village', ['village_id'], ['id'])
    op.drop_index(op.f('ix_village_resource_storage_village_id'), table_name='village_resource_storage')
    op.alter_column('village_resource_storage', 'last_updated',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_constraint(None, 'village_farm_plots', type_='foreignkey')
    op.create_foreign_key(op.f('village_farm_plots_village_id_fkey'), 'village_farm_plots', 'village', ['village_id'], ['id'])
    op.drop_constraint('uq_village_farm_slot', 'village_farm_plots', type_='unique')
    op.drop_index(op.f('ix_village_farm_plots_village_id'), table_name='village_farm_plots')
    op.create_unique_constraint(op.f('uq_village_farm'), 'village_farm_plots', ['village_id', 'resource_type_id', 'farm_number'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_owner_village_name', 'village', type_='unique')
    op.drop_index(op.f('ix_village_owner_id'), table_name='village')
    op.alter_column('village', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.alter_column('tribe_attributes', 'name',
               existing_type=sa.Enum('Romans', 'Teutons', 'Gauls', name='tribe_enum', native_enum=False, length=20),
               type_=postgresql.ENUM('ROMANS', 'TEUTONS', 'GAULS', name='tribe'),
               existing_nullable=False)
    op.alter_column('resources_types', 'name',
               existing_type=sa.Enum('Wood', 'Clay', 'Iron', 'Crop', name='resource_enum', native_enum=False, length=20),
               type_=postgresql.ENUM('WOOD', 'CLAY', 'IRON', 'CROP', name='resource'),
               existing_nullable=False)
    op.drop_constraint('uq_building_type_name_tribe', 'building_type', type_='unique')
    op.create_unique_constraint(op.f('uq_buildingtype_name_tribe'), 'building_type', ['name', 'tribe_id'], postgresql_nulls_not_distinct=False)
    op.add_column('building_level', sa.Column('construction_time', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('building_level', sa.Column('population_required', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'building_level', type_='foreignkey')
    op.create_foreign_key(op.f('building_level_building_type_id_fkey'), 'building_level', 'building_type', ['building_type_id'], ['id'])
    op.drop_index(op.f('ix_building_level_building_type_id'), table_name='building_level')
    op.drop_column('building_level', 'population_increase')
    op.drop_column('building_level', 'construction_time_seconds')
    op.create_table('production',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('resource_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('production_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], name=op.f('production_resource_type_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('production_pkey')),
    sa.UniqueConstraint('resource_type_id', 'level', name=op.f('uq_resource_level'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('building_upgrade_resource',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('building_level_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('resource_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['building_level_id'], ['building_level.id'], name=op.f('building_upgrade_resource_building_level_id_fkey')),
    sa.ForeignKeyConstraint(['resource_type_id'], ['resources_types.id'], name=op.f('building_upgrade_resource_resource_type_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('building_upgrade_resource_pkey')),
    sa.UniqueConstraint('building_level_id', 'resource_type_id', name=op.f('uq_building_upgrade'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_building_upgrade_resource_building_level_id'), 'building_upgrade_resource', ['building_level_id'], unique=False)
    op.drop_index(op.f('ix_village_resource_transaction_entry_transaction_id'), table_name='village_resource_transaction_entry')
    op.drop_table('village_resource_transaction_entry')
    op.drop_index(op.f('ix_village_farm_upgrade_village_farm_plot_id'), table_name='village_farm_upgrade')
    op.drop_index(op.f('ix_village_farm_upgrade_status'), table_name='village_farm_upgrade')
    op.drop_index(op.f('ix_village_farm_upgrade_completes_at'), table_name='village_farm_upgrade')
    op.drop_index('ix_farm_upgrade_plot_status', table_name='village_farm_upgrade')
    op.drop_table('village_farm_upgrade')
    op.drop_index(op.f('ix_village_building_upgrade_village_building_id'), table_name='village_building_upgrade')
    op.drop_index(op.f('ix_village_building_upgrade_status'), table_name='village_building_upgrade')
    op.drop_index(op.f('ix_village_building_upgrade_completes_at'), table_name='village_building_upgrade')
    op.drop_index('ix_building_upgrade_target_status', table_name='village_building_upgrade')
    op.drop_table('village_building_upgrade')
    op.drop_index(op.f('ix_village_resource_transaction_village_id'), table_name='village_resource_transaction')
    op.drop_index(op.f('ix_village_resource_transaction_transaction_type'), table_name='village_resource_transaction')
    op.drop_index(op.f('ix_village_resource_transaction_created_at'), table_name='village_resource_transaction')
    op.drop_index('ix_resource_transaction_source', table_name='village_resource_transaction')
    op.drop_table('village_resource_transaction')
    op.drop_index(op.f('ix_village_building_village_id'), table_name='village_building')
    op.drop_table('village_building')
    op.drop_index(op.f('ix_building_level_cost_building_level_id'), table_name='building_level_cost')
    op.drop_table('building_level_cost')
    op.drop_index(op.f('ix_farm_level_cost_farm_level_id'), table_name='farm_level_cost')
    op.drop_table('farm_level_cost')
    op.drop_index(op.f('ix_farm_level_farm_resource_type_id'), table_name='farm_level')
    op.drop_table('farm_level')
    # ### end Alembic commands ###
