events {
  worker_connections    4096; ## Default: 1024
}

http {
  include               /etc/nginx/mime.types;
  server {
    listen              80;
    server_name         example.com;

    location / {
      root              /usr/share/nginx/html;
      index             index.html index.htm;
      #                 ensures that any request not matching a file is redirected to index.html.
      try_files         $uri /index.html;
    }
  }
}
